### ISSUE TITLE
Добавить галерею в pyramid_sacrud_example

### ISSUE THREAD

**Issue by uralbash** [itcase/ps_gallery#3]
Поменять main на includeme см. pyramid_sacrud.**init**.py
DBSession можно брать из реквеста(request.dbsession), его добавляет pyramid_sacrud здесь https://github.com/ITCase/pyramid_sacrud/blob/develop/pyramid_sacrud/includes/database.py#L22

**Comment by petrikoz** [comment]
Добавил. Но сломалось в админке при добавлении нового изображения в галлерею. Что-то с ключами ему не нравится. Запрашиваю помощь @uralbash
